export const SET_CURRENT_ROOM = 'SET_CURRENT_ROOM';
export const SET_CURRENT_ROOM_ERROR = 'SET_CURRENT_ROOM_ERROR';

export const SET_PEERS = 'SET_PEERS';
export const SET_PEERS_ERROR = 'SET_PEERS_ERROR';

export const ADD_CONNECTION = 'ADD_CONNECTION';
export const REMOVE_CONNECTION = 'REMOVE_CONNECTION';
export const SET_CONNECTIONS_ERROR = 'SET_CONNECTIONS_ERROR';

export const SET_CALLS = 'SET_CALLS';
export const SET_CALLS_ERROR = 'SET_CALLS_ERROR';

export const INIT_LOCAL_USER_SOCKET = 'INIT_LOCAL_USER_SOCKET';
export const INIT_LOCAL_USER_PEER = 'INIT_LOCAL_USER_PEER';
export const SET_LOCAL_USER_METADATA = 'SET_LOCAL_USER_METADATA';
export const SET_LOCAL_USER_ERROR = 'SET_LOCAL_USER_ERROR';
