export const ADD_PEER = 'ADD_PEER';
export const REMOVE_PEER = 'REMOVE_PEER';
export const SET_PEERS_ERROR = 'SET_PEERS_ERROR';

export const ADD_CONNECTION = 'ADD_CONNECTION';
export const REMOVE_CONNECTION = 'REMOVE_CONNECTION';
export const SET_CONNECTIONS_ERROR = 'SET_CONNECTIONS_ERROR';

export const ADD_CALL = 'ADD_CALL';
export const REMOVE_CALL = 'REMOVE_CALL';
export const SET_CALLS_ERROR = 'SET_CALLS_ERROR';

export const ADD_STREAM = 'ADD_STREAM';
export const REMOVE_STREAM = 'REMOVE_STREAM';
export const SET_STREAMS_ERROR = 'SET_STREAM_ERROR';
export const CLEAR_ALL_STREAMS = 'CLEAR_ALL_STREAMS';

export const SET_CURRENT_ROOM = 'SET_CURRENT_ROOM';
export const SET_CURRENT_ROOM_ERROR = 'SET_CURRENT_ROOM_ERROR';

export const SET_LOCAL_USER_LOADING = 'SET_LOCAL_USER_LOADING';
export const INIT_LOCAL_USER_SOCKET = 'INIT_LOCAL_USER_SOCKET';
export const INIT_LOCAL_USER_PEER = 'INIT_LOCAL_USER_PEER';
export const SET_LOCAL_USER_METADATA = 'SET_LOCAL_USER_METADATA';
export const SET_LOCAL_USER_ERROR = 'SET_LOCAL_USER_ERROR';
export const RESET_LOCAL_USER = 'RESET_LOCAL_USER';

export const SET_PLUGIN = 'SET_PLUGIN';
export const SET_PLUGIN_ERROR = 'SET_PLUGIN_ERROR';

export const ADD_NEW_MESSAGE = 'ADD_NEW_MESSAGE';
